// Turns the Phosphor SVG files into one TypeScript
// module of named icons. Run by the pre-scripts in
// package.json. The output is not committed.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const assetsFolder = 'node_modules/@phosphor-icons/core/assets'
const outputPath = 'src/icons/generated.ts'
const boldSuffix = '-bold.svg'

// Every Phosphor bold and fill icon is drawn with
// path elements only, so an icon is stored as its
// list of path shapes.
const readPathShapes = (kind, iconName) => {
	const filePath = join(assetsFolder, kind, `${iconName}-${kind}.svg`)
	const svgText = readFileSync(filePath, 'utf8')
	const pathMatches = [...svgText.matchAll(/<path d="([^"]+)"/g)]
	const hasPaths = pathMatches.length > 0
	if (!hasPaths) throw new Error(`No paths found in ${filePath}`)
	return pathMatches.map((pathMatch) => pathMatch[1])
}

// 'arrow-left' becomes 'arrowLeftIcon'. The suffix
// keeps names like 'function' and 'export' legal.
const getExportName = (iconName) => {
	const upperCaseAfterDash = (match, letter) => letter.toUpperCase()
	const camelName = iconName.replace(/-([a-z0-9])/g, upperCaseAfterDash)
	return `${camelName}Icon`
}

const buildExportLine = (iconName) => {
	const exportName = getExportName(iconName)
	const boldShapes = readPathShapes('bold', iconName)
	const fillShapes = readPathShapes('fill', iconName)
	const icon = { name: iconName, bold: boldShapes, fill: fillShapes }
	return `export const ${exportName}: IconT = ${JSON.stringify(icon)}`
}

const boldFiles = readdirSync(join(assetsFolder, 'bold'))
const iconNames = boldFiles.map((fileName) => fileName.slice(0, -boldSuffix.length)).sort()
const exportLines = iconNames.map(buildExportLine)

const header = [
	'// Generated by scripts/build-icons.mjs. Do not edit.',
	'// Icons are from Phosphor Icons, MIT license.',
	"import type { IconT } from './icon-type'",
	''
]

writeFileSync(outputPath, [...header, ...exportLines, ''].join('\n'))
console.log(`Wrote ${iconNames.length} icons to ${outputPath}`)
